name:                generic-cs221
version:             0.1.0.0
github:              "bhaktishh/generic-cs221"
license:             BSD3
author:              "Bhakti Shah"
maintainer:          "shahbhakti21@gmail.com"
copyright:           "Bhakti Shah"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bhaktishh/generic-cs221#readme>

dependencies:
- base >= 4.7 && < 5
- syb

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -XDeriveDataTypeable
- -XRankNTypes

library:
  source-dirs: src

executables:
  generic-cs221-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-cs221

tests:
  generic-cs221-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-cs221
